language: python

# setup environment variables container before building
# before_install:
  
python:
  - "3.6.1"


# command to install dependencies
install: "pip install -r requirements.txt"


# environment variables 
env:
  global:
    - STRIPE_SECRET_KEY="SAMPLESTRIPEKEY"
    - GA_ID="GARBAGE"

# run tests
script: 
  python test/*.py
